import v0 from './nfts/Squishiverse/Archer.mp4'
import v1 from './nfts/Squishiverse/Dragon Knight.mp4'
import v2 from './nfts/Squishiverse/Green Demon.mp4'
import v3 from './nfts/Squishiverse/IronSquish.mp4'
import v4 from './nfts/Squishiverse/King Squishie.mp4'
import v5 from './nfts/Squishiverse/Moon Angel.mp4'
import v6 from './nfts/Squishiverse/Pepe.mp4'
import v7 from './nfts/Squishiverse/Protector of the Squishiverse.mp4'
import v8 from './nfts/Squishiverse/Red Demon.mp4'
import v9 from './nfts/Squishiverse/Sun Angel.mp4'

export const Squishiverse_Vids = [ v0, v1, v2, v3, v4, v5, v6, v7, v8, v9 ]

import i0 from './nfts/Squishiverse/unnamed (1).png'
import i1 from './nfts/Squishiverse/unnamed (2).png'
import i2 from './nfts/Squishiverse/unnamed (3).png'
import i3 from './nfts/Squishiverse/unnamed (4).png'
import i4 from './nfts/Squishiverse/unnamed (5).png'
import i5 from './nfts/Squishiverse/unnamed (6).png'
import i6 from './nfts/Squishiverse/unnamed (7).png'
import i7 from './nfts/Squishiverse/unnamed (8).png'
import i8 from './nfts/Squishiverse/unnamed (9).png'
import i9 from './nfts/Squishiverse/unnamed (10).png'
import i10 from './nfts/Squishiverse/unnamed (11).png'
import i11 from './nfts/Squishiverse/unnamed (12).png'
import i12 from './nfts/Squishiverse/unnamed (13).png'
import i13 from './nfts/Squishiverse/unnamed (14).png'
import i14 from './nfts/Squishiverse/unnamed.png'

export const Squishiverse_Imgs = [ i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14 ]

import a0 from './nfts/arc/ARC_R_17_White.jpg'
import a1 from './nfts/arc/ARC_R_20_White.jpg'
import a2 from './nfts/arc/ARC_R_23_White.jpg'
import a3 from './nfts/arc/ARC_R_34_White.jpg'
import a4 from './nfts/arc/ARC_R_35_White.jpg'
import a5 from './nfts/arc/ARC_R_36_White.jpg'
import a6 from './nfts/arc/ARC_R_40_White.jpg'
import a7 from './nfts/arc/ARC_R_44_White.jpg'
import a8 from './nfts/arc/ARC_R_55_White.jpg'
import a9 from './nfts/arc/ARC_R_57_White.jpg'

export const Arc_Imgs = [ a0, a1, a2, a3, a4, a5, a6, a7, a8, a9 ]

import c0 from './nfts/Chubbicorns/8.png'
import c1 from './nfts/Chubbicorns/22.png'
import c2 from './nfts/Chubbicorns/30.png'
import c3 from './nfts/Chubbicorns/42.png'
import c4 from './nfts/Chubbicorns/51.png'
import c5 from './nfts/Chubbicorns/75.png'
import c6 from './nfts/Chubbicorns/80.png'
import c7 from './nfts/Chubbicorns/88.png'
import c8 from './nfts/Chubbicorns/94.png'
import c9 from './nfts/Chubbicorns/96.png'
import c10 from './nfts/Chubbicorns/100.png'
import c11 from './nfts/Chubbicorns/132.png'
import c12 from './nfts/Chubbicorns/142.png'
import c13 from './nfts/Chubbicorns/156.png'
import c14 from './nfts/Chubbicorns/219.png'
import c15 from './nfts/Chubbicorns/228.png'
import c16 from './nfts/Chubbicorns/230.png'
import c17 from './nfts/Chubbicorns/232.png'
import c18 from './nfts/Chubbicorns/247.png'
import c19 from './nfts/Chubbicorns/249.png'

export const Chubbi_Imgs = [ c0, c1, c2 ,c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19 ]

import f0 from './nfts/Frens/1205.png'
import f1 from './nfts/Frens/1917.png'
import f2 from './nfts/Frens/2858.png'
import f3 from './nfts/Frens/3362.png'
import f4 from './nfts/Frens/4105.png'
import f5 from './nfts/Frens/4106.png'
import f6 from './nfts/Frens/5299.png'
import f7 from './nfts/Frens/5725.png'
import f8 from './nfts/Frens/5924.png'
import f9 from './nfts/Frens/5929.png'
import f10 from './nfts/Frens/7016.png'
import f11 from './nfts/Frens/7074.png'
import f12 from './nfts/Frens/7220.png'
import f13 from './nfts/Frens/7331.png'
import f14 from './nfts/Frens/7455.png'
import f15 from './nfts/Frens/7774.png'
import f16 from './nfts/Frens/7790.png'
import f17 from './nfts/Frens/8571.png'
import f18 from './nfts/Frens/8663.png'
import f19 from './nfts/Frens/8757.png'

export const Frens_Imgs = [ f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f19 ]

import l0 from './nfts/Lucky Zero/506.png'
import l1 from './nfts/Lucky Zero/719.png'
import l2 from './nfts/Lucky Zero/911.png'
import l3 from './nfts/Lucky Zero/984.png'
import l4 from './nfts/Lucky Zero/1061.png'
import l5 from './nfts/Lucky Zero/1134.png'
import l6 from './nfts/Lucky Zero/1310.png'
import l7 from './nfts/Lucky Zero/1474.png'
import l8 from './nfts/Lucky Zero/1688.png'
import l9 from './nfts/Lucky Zero/1999.png'
import l10 from './nfts/Lucky Zero/2012.png'
import l11 from './nfts/Lucky Zero/2093.png'
import l12 from './nfts/Lucky Zero/2165.png'
import l13 from './nfts/Lucky Zero/2238.png'
import l14 from './nfts/Lucky Zero/2334.png'
import l15 from './nfts/Lucky Zero/2361.png'
import l16 from './nfts/Lucky Zero/2705.png'
import l17 from './nfts/Lucky Zero/2922.png'
import l18 from './nfts/Lucky Zero/3244.png'
import l19 from './nfts/Lucky Zero/3259.png'

export const Lucky_Imgs = [ l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18, l19 ]

export const NFT_Imgs = [ ...Squishiverse_Imgs, ...Arc_Imgs, ...Chubbi_Imgs, ...Frens_Imgs, ...Lucky_Imgs ]

export const All_NFTS = [ ...NFT_Imgs, ...Squishiverse_Vids ]